/**
 * This class is generated by jOOQ
 */
package com.josh2112.inotesmonitor.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotesMessage extends org.jooq.impl.TableImpl<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -499648630;

	/**
	 * The singleton instance of <code>NotesMessage</code>
	 */
	public static final com.josh2112.inotesmonitor.database.tables.NotesMessage NotesMessage = new com.josh2112.inotesmonitor.database.tables.NotesMessage();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecord> getRecordType() {
		return com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecord.class;
	}

	/**
	 * The column <code>NotesMessage.GUID</code>.
	 */
	public final org.jooq.TableField<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecord, java.lang.String> GUID = createField("GUID", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>NotesMessage.MessageType</code>.
	 */
	public final org.jooq.TableField<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecord, com.josh2112.inotesmonitor.inotesdata.NotesMessage.MessageType> MessageType = createField("MessageType", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "", new com.josh2112.utils.jooq.MessageTypeConverter());

	/**
	 * The column <code>NotesMessage.IsRead</code>.
	 */
	public final org.jooq.TableField<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecord, java.lang.Boolean> IsRead = createField("IsRead", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "", new com.josh2112.utils.jooq.BooleanConverter());

	/**
	 * The column <code>NotesMessage.Date</code>.
	 */
	public final org.jooq.TableField<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecord, java.time.LocalDateTime> Date = createField("Date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "", new com.josh2112.utils.jooq.LocalDateTimeConverter());

	/**
	 * The column <code>NotesMessage.Sender</code>.
	 */
	public final org.jooq.TableField<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecord, java.lang.String> Sender = createField("Sender", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>NotesMessage.Subject</code>.
	 */
	public final org.jooq.TableField<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecord, java.lang.String> Subject = createField("Subject", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>NotesMessage.Body</code>.
	 */
	public final org.jooq.TableField<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecord, java.lang.String> Body = createField("Body", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>NotesMessage</code> table reference
	 */
	public NotesMessage() {
		this("NotesMessage", null);
	}

	/**
	 * Create an aliased <code>NotesMessage</code> table reference
	 */
	public NotesMessage(java.lang.String alias) {
		this(alias, com.josh2112.inotesmonitor.database.tables.NotesMessage.NotesMessage);
	}

	private NotesMessage(java.lang.String alias, org.jooq.Table<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecord> aliased) {
		this(alias, aliased, null);
	}

	private NotesMessage(java.lang.String alias, org.jooq.Table<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.josh2112.inotesmonitor.database.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecord> getPrimaryKey() {
		return com.josh2112.inotesmonitor.database.Keys.pk_NotesMessage;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecord>>asList(com.josh2112.inotesmonitor.database.Keys.pk_NotesMessage);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.josh2112.inotesmonitor.database.tables.NotesMessage as(java.lang.String alias) {
		return new com.josh2112.inotesmonitor.database.tables.NotesMessage(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.josh2112.inotesmonitor.database.tables.NotesMessage rename(java.lang.String name) {
		return new com.josh2112.inotesmonitor.database.tables.NotesMessage(name, null);
	}
}
