/**
 * This class is generated by jOOQ
 */
package com.josh2112.inotesmonitor.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotesMessageRecipient extends org.jooq.impl.TableImpl<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecipientRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -1181882084;

	/**
	 * The singleton instance of <code>NotesMessageRecipient</code>
	 */
	public static final com.josh2112.inotesmonitor.database.tables.NotesMessageRecipient NotesMessageRecipient = new com.josh2112.inotesmonitor.database.tables.NotesMessageRecipient();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecipientRecord> getRecordType() {
		return com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecipientRecord.class;
	}

	/**
	 * The column <code>NotesMessageRecipient.ID</code>.
	 */
	public final org.jooq.TableField<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecipientRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>NotesMessageRecipient.GUID</code>.
	 */
	public final org.jooq.TableField<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecipientRecord, java.lang.String> GUID = createField("GUID", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>NotesMessageRecipient.Name</code>.
	 */
	public final org.jooq.TableField<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecipientRecord, java.lang.String> Name = createField("Name", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

	/**
	 * Create a <code>NotesMessageRecipient</code> table reference
	 */
	public NotesMessageRecipient() {
		this("NotesMessageRecipient", null);
	}

	/**
	 * Create an aliased <code>NotesMessageRecipient</code> table reference
	 */
	public NotesMessageRecipient(java.lang.String alias) {
		this(alias, com.josh2112.inotesmonitor.database.tables.NotesMessageRecipient.NotesMessageRecipient);
	}

	private NotesMessageRecipient(java.lang.String alias, org.jooq.Table<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecipientRecord> aliased) {
		this(alias, aliased, null);
	}

	private NotesMessageRecipient(java.lang.String alias, org.jooq.Table<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecipientRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.josh2112.inotesmonitor.database.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecipientRecord> getPrimaryKey() {
		return com.josh2112.inotesmonitor.database.Keys.pk_NotesMessageRecipient;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecipientRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecipientRecord>>asList(com.josh2112.inotesmonitor.database.Keys.pk_NotesMessageRecipient);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecipientRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecipientRecord, ?>>asList(com.josh2112.inotesmonitor.database.Keys.fk_NotesMessageRecipient_NotesMessage_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.josh2112.inotesmonitor.database.tables.NotesMessageRecipient as(java.lang.String alias) {
		return new com.josh2112.inotesmonitor.database.tables.NotesMessageRecipient(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.josh2112.inotesmonitor.database.tables.NotesMessageRecipient rename(java.lang.String name) {
		return new com.josh2112.inotesmonitor.database.tables.NotesMessageRecipient(name, null);
	}
}
