/**
 * This class is generated by jOOQ
 */
package com.josh2112.inotesmonitor.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotesMeetingDetails extends org.jooq.impl.TableImpl<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -1517139530;

	/**
	 * The singleton instance of <code>NotesMeetingDetails</code>
	 */
	public static final com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails NotesMeetingDetails = new com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord> getRecordType() {
		return com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord.class;
	}

	/**
	 * The column <code>NotesMeetingDetails.ID</code>.
	 */
	public final org.jooq.TableField<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>NotesMeetingDetails.MeetingId</code>.
	 */
	public final org.jooq.TableField<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord, java.lang.String> MeetingId = createField("MeetingId", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>NotesMeetingDetails.GUID</code>.
	 */
	public final org.jooq.TableField<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord, java.lang.String> GUID = createField("GUID", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>NotesMeetingDetails.Chair</code>.
	 */
	public final org.jooq.TableField<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord, java.lang.String> Chair = createField("Chair", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>NotesMeetingDetails.Topic</code>.
	 */
	public final org.jooq.TableField<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord, java.lang.String> Topic = createField("Topic", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>NotesMeetingDetails.Location</code>.
	 */
	public final org.jooq.TableField<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord, java.lang.String> Location = createField("Location", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>NotesMeetingDetails.StartDate</code>.
	 */
	public final org.jooq.TableField<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord, java.time.LocalDateTime> StartDate = createField("StartDate", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "", new com.josh2112.utils.jooq.LocalDateTimeConverter());

	/**
	 * The column <code>NotesMeetingDetails.EndDate</code>.
	 */
	public final org.jooq.TableField<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord, java.time.LocalDateTime> EndDate = createField("EndDate", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "", new com.josh2112.utils.jooq.LocalDateTimeConverter());

	/**
	 * Create a <code>NotesMeetingDetails</code> table reference
	 */
	public NotesMeetingDetails() {
		this("NotesMeetingDetails", null);
	}

	/**
	 * Create an aliased <code>NotesMeetingDetails</code> table reference
	 */
	public NotesMeetingDetails(java.lang.String alias) {
		this(alias, com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails.NotesMeetingDetails);
	}

	private NotesMeetingDetails(java.lang.String alias, org.jooq.Table<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord> aliased) {
		this(alias, aliased, null);
	}

	private NotesMeetingDetails(java.lang.String alias, org.jooq.Table<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.josh2112.inotesmonitor.database.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord> getPrimaryKey() {
		return com.josh2112.inotesmonitor.database.Keys.pk_NotesMeetingDetails;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord>>asList(com.josh2112.inotesmonitor.database.Keys.pk_NotesMeetingDetails);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord, ?>>asList(com.josh2112.inotesmonitor.database.Keys.fk_NotesMeetingDetails_NotesMessage_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails as(java.lang.String alias) {
		return new com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails rename(java.lang.String name) {
		return new com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails(name, null);
	}
}
