/**
 * This class is generated by jOOQ
 */
package com.josh2112.inotesmonitor.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotesMeetingAttendee extends org.jooq.impl.TableImpl<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingAttendeeRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 1097439828;

	/**
	 * The singleton instance of <code>NotesMeetingAttendee</code>
	 */
	public static final com.josh2112.inotesmonitor.database.tables.NotesMeetingAttendee NotesMeetingAttendee = new com.josh2112.inotesmonitor.database.tables.NotesMeetingAttendee();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingAttendeeRecord> getRecordType() {
		return com.josh2112.inotesmonitor.database.tables.records.NotesMeetingAttendeeRecord.class;
	}

	/**
	 * The column <code>NotesMeetingAttendee.ID</code>.
	 */
	public final org.jooq.TableField<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingAttendeeRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>NotesMeetingAttendee.MeetingDetailsId</code>.
	 */
	public final org.jooq.TableField<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingAttendeeRecord, java.lang.Integer> MeetingDetailsId = createField("MeetingDetailsId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>NotesMeetingAttendee.Name</code>.
	 */
	public final org.jooq.TableField<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingAttendeeRecord, java.lang.String> Name = createField("Name", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

	/**
	 * Create a <code>NotesMeetingAttendee</code> table reference
	 */
	public NotesMeetingAttendee() {
		this("NotesMeetingAttendee", null);
	}

	/**
	 * Create an aliased <code>NotesMeetingAttendee</code> table reference
	 */
	public NotesMeetingAttendee(java.lang.String alias) {
		this(alias, com.josh2112.inotesmonitor.database.tables.NotesMeetingAttendee.NotesMeetingAttendee);
	}

	private NotesMeetingAttendee(java.lang.String alias, org.jooq.Table<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingAttendeeRecord> aliased) {
		this(alias, aliased, null);
	}

	private NotesMeetingAttendee(java.lang.String alias, org.jooq.Table<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingAttendeeRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.josh2112.inotesmonitor.database.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingAttendeeRecord> getPrimaryKey() {
		return com.josh2112.inotesmonitor.database.Keys.pk_NotesMeetingAttendee;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingAttendeeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingAttendeeRecord>>asList(com.josh2112.inotesmonitor.database.Keys.pk_NotesMeetingAttendee);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingAttendeeRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingAttendeeRecord, ?>>asList(com.josh2112.inotesmonitor.database.Keys.fk_NotesMeetingAttendee_NotesMeetingDetails_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.josh2112.inotesmonitor.database.tables.NotesMeetingAttendee as(java.lang.String alias) {
		return new com.josh2112.inotesmonitor.database.tables.NotesMeetingAttendee(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.josh2112.inotesmonitor.database.tables.NotesMeetingAttendee rename(java.lang.String name) {
		return new com.josh2112.inotesmonitor.database.tables.NotesMeetingAttendee(name, null);
	}
}
