/**
 * This class is generated by jOOQ
 */
package com.josh2112.inotesmonitor.database.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotesMeetingAttendeeRecord extends org.jooq.impl.UpdatableRecordImpl<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingAttendeeRecord> implements java.io.Serializable, java.lang.Cloneable, org.jooq.Record3<java.lang.Integer, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = 1948679598;

	/**
	 * Setter for <code>NotesMeetingAttendee.ID</code>.
	 */
	public void setID(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>NotesMeetingAttendee.ID</code>.
	 */
	public java.lang.Integer getID() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>NotesMeetingAttendee.MeetingDetailsId</code>.
	 */
	public void setMeetingDetailsId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>NotesMeetingAttendee.MeetingDetailsId</code>.
	 */
	public java.lang.Integer getMeetingDetailsId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>NotesMeetingAttendee.Name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>NotesMeetingAttendee.Name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.josh2112.inotesmonitor.database.tables.NotesMeetingAttendee.NotesMeetingAttendee.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.josh2112.inotesmonitor.database.tables.NotesMeetingAttendee.NotesMeetingAttendee.MeetingDetailsId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.josh2112.inotesmonitor.database.tables.NotesMeetingAttendee.NotesMeetingAttendee.Name;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getID();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getMeetingDetailsId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMeetingAttendeeRecord value1(java.lang.Integer value) {
		setID(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMeetingAttendeeRecord value2(java.lang.Integer value) {
		setMeetingDetailsId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMeetingAttendeeRecord value3(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMeetingAttendeeRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached NotesMeetingAttendeeRecord
	 */
	public NotesMeetingAttendeeRecord() {
		super(com.josh2112.inotesmonitor.database.tables.NotesMeetingAttendee.NotesMeetingAttendee);
	}

	/**
	 * Create a detached, initialised NotesMeetingAttendeeRecord
	 */
	public NotesMeetingAttendeeRecord(java.lang.Integer ID, java.lang.Integer MeetingDetailsId, java.lang.String Name) {
		super(com.josh2112.inotesmonitor.database.tables.NotesMeetingAttendee.NotesMeetingAttendee);

		setValue(0, ID);
		setValue(1, MeetingDetailsId);
		setValue(2, Name);
	}
}
