/**
 * This class is generated by jOOQ
 */
package com.josh2112.inotesmonitor.database.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotesMeetingDetailsRecord extends org.jooq.impl.UpdatableRecordImpl<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord> implements java.io.Serializable, java.lang.Cloneable, org.jooq.Record8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.time.LocalDateTime, java.time.LocalDateTime> {

	private static final long serialVersionUID = 766294788;

	/**
	 * Setter for <code>NotesMeetingDetails.ID</code>.
	 */
	public void setID(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>NotesMeetingDetails.ID</code>.
	 */
	public java.lang.Integer getID() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>NotesMeetingDetails.MeetingId</code>.
	 */
	public void setMeetingId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>NotesMeetingDetails.MeetingId</code>.
	 */
	public java.lang.String getMeetingId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>NotesMeetingDetails.GUID</code>.
	 */
	public void setGUID(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>NotesMeetingDetails.GUID</code>.
	 */
	public java.lang.String getGUID() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>NotesMeetingDetails.Chair</code>.
	 */
	public void setChair(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>NotesMeetingDetails.Chair</code>.
	 */
	public java.lang.String getChair() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>NotesMeetingDetails.Topic</code>.
	 */
	public void setTopic(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>NotesMeetingDetails.Topic</code>.
	 */
	public java.lang.String getTopic() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>NotesMeetingDetails.Location</code>.
	 */
	public void setLocation(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>NotesMeetingDetails.Location</code>.
	 */
	public java.lang.String getLocation() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>NotesMeetingDetails.StartDate</code>.
	 */
	public void setStartDate(java.time.LocalDateTime value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>NotesMeetingDetails.StartDate</code>.
	 */
	public java.time.LocalDateTime getStartDate() {
		return (java.time.LocalDateTime) getValue(6);
	}

	/**
	 * Setter for <code>NotesMeetingDetails.EndDate</code>.
	 */
	public void setEndDate(java.time.LocalDateTime value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>NotesMeetingDetails.EndDate</code>.
	 */
	public java.time.LocalDateTime getEndDate() {
		return (java.time.LocalDateTime) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.time.LocalDateTime, java.time.LocalDateTime> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.time.LocalDateTime, java.time.LocalDateTime> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails.NotesMeetingDetails.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails.NotesMeetingDetails.MeetingId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails.NotesMeetingDetails.GUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails.NotesMeetingDetails.Chair;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails.NotesMeetingDetails.Topic;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails.NotesMeetingDetails.Location;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.time.LocalDateTime> field7() {
		return com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails.NotesMeetingDetails.StartDate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.time.LocalDateTime> field8() {
		return com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails.NotesMeetingDetails.EndDate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getID();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getMeetingId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getGUID();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getChair();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getTopic();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getLocation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.time.LocalDateTime value7() {
		return getStartDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.time.LocalDateTime value8() {
		return getEndDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMeetingDetailsRecord value1(java.lang.Integer value) {
		setID(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMeetingDetailsRecord value2(java.lang.String value) {
		setMeetingId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMeetingDetailsRecord value3(java.lang.String value) {
		setGUID(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMeetingDetailsRecord value4(java.lang.String value) {
		setChair(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMeetingDetailsRecord value5(java.lang.String value) {
		setTopic(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMeetingDetailsRecord value6(java.lang.String value) {
		setLocation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMeetingDetailsRecord value7(java.time.LocalDateTime value) {
		setStartDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMeetingDetailsRecord value8(java.time.LocalDateTime value) {
		setEndDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMeetingDetailsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.time.LocalDateTime value7, java.time.LocalDateTime value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached NotesMeetingDetailsRecord
	 */
	public NotesMeetingDetailsRecord() {
		super(com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails.NotesMeetingDetails);
	}

	/**
	 * Create a detached, initialised NotesMeetingDetailsRecord
	 */
	public NotesMeetingDetailsRecord(java.lang.Integer ID, java.lang.String MeetingId, java.lang.String GUID, java.lang.String Chair, java.lang.String Topic, java.lang.String Location, java.time.LocalDateTime StartDate, java.time.LocalDateTime EndDate) {
		super(com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails.NotesMeetingDetails);

		setValue(0, ID);
		setValue(1, MeetingId);
		setValue(2, GUID);
		setValue(3, Chair);
		setValue(4, Topic);
		setValue(5, Location);
		setValue(6, StartDate);
		setValue(7, EndDate);
	}
}
