/**
 * This class is generated by jOOQ
 */
package com.josh2112.inotesmonitor.database;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends org.jooq.impl.SchemaImpl implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -813910362;

	/**
	 * The singleton instance of <code></code>
	 */
	public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

	/**
	 * No further instances allowed
	 */
	private DefaultSchema() {
		super("");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.josh2112.inotesmonitor.database.tables.NotesMeetingAttendee.NotesMeetingAttendee,
			com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails.NotesMeetingDetails,
			com.josh2112.inotesmonitor.database.tables.NotesMessage.NotesMessage,
			com.josh2112.inotesmonitor.database.tables.NotesMessageRecipient.NotesMessageRecipient);
	}
}
