/**
 * This class is generated by jOOQ
 */
package com.josh2112.inotesmonitor.database;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code></code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingAttendeeRecord> pk_NotesMeetingAttendee = UniqueKeys0.pk_NotesMeetingAttendee;
	public static final org.jooq.UniqueKey<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord> pk_NotesMeetingDetails = UniqueKeys0.pk_NotesMeetingDetails;
	public static final org.jooq.UniqueKey<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecord> pk_NotesMessage = UniqueKeys0.pk_NotesMessage;
	public static final org.jooq.UniqueKey<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecipientRecord> pk_NotesMessageRecipient = UniqueKeys0.pk_NotesMessageRecipient;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingAttendeeRecord, com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord> fk_NotesMeetingAttendee_NotesMeetingDetails_1 = ForeignKeys0.fk_NotesMeetingAttendee_NotesMeetingDetails_1;
	public static final org.jooq.ForeignKey<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord, com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecord> fk_NotesMeetingDetails_NotesMessage_1 = ForeignKeys0.fk_NotesMeetingDetails_NotesMessage_1;
	public static final org.jooq.ForeignKey<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecipientRecord, com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecord> fk_NotesMessageRecipient_NotesMessage_1 = ForeignKeys0.fk_NotesMessageRecipient_NotesMessage_1;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingAttendeeRecord> pk_NotesMeetingAttendee = createUniqueKey(com.josh2112.inotesmonitor.database.tables.NotesMeetingAttendee.NotesMeetingAttendee, com.josh2112.inotesmonitor.database.tables.NotesMeetingAttendee.NotesMeetingAttendee.ID);
		public static final org.jooq.UniqueKey<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord> pk_NotesMeetingDetails = createUniqueKey(com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails.NotesMeetingDetails, com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails.NotesMeetingDetails.ID);
		public static final org.jooq.UniqueKey<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecord> pk_NotesMessage = createUniqueKey(com.josh2112.inotesmonitor.database.tables.NotesMessage.NotesMessage, com.josh2112.inotesmonitor.database.tables.NotesMessage.NotesMessage.GUID);
		public static final org.jooq.UniqueKey<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecipientRecord> pk_NotesMessageRecipient = createUniqueKey(com.josh2112.inotesmonitor.database.tables.NotesMessageRecipient.NotesMessageRecipient, com.josh2112.inotesmonitor.database.tables.NotesMessageRecipient.NotesMessageRecipient.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingAttendeeRecord, com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord> fk_NotesMeetingAttendee_NotesMeetingDetails_1 = createForeignKey(com.josh2112.inotesmonitor.database.Keys.pk_NotesMeetingDetails, com.josh2112.inotesmonitor.database.tables.NotesMeetingAttendee.NotesMeetingAttendee, com.josh2112.inotesmonitor.database.tables.NotesMeetingAttendee.NotesMeetingAttendee.MeetingDetailsId);
		public static final org.jooq.ForeignKey<com.josh2112.inotesmonitor.database.tables.records.NotesMeetingDetailsRecord, com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecord> fk_NotesMeetingDetails_NotesMessage_1 = createForeignKey(com.josh2112.inotesmonitor.database.Keys.pk_NotesMessage, com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails.NotesMeetingDetails, com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails.NotesMeetingDetails.GUID);
		public static final org.jooq.ForeignKey<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecipientRecord, com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecord> fk_NotesMessageRecipient_NotesMessage_1 = createForeignKey(com.josh2112.inotesmonitor.database.Keys.pk_NotesMessage, com.josh2112.inotesmonitor.database.tables.NotesMessageRecipient.NotesMessageRecipient, com.josh2112.inotesmonitor.database.tables.NotesMessageRecipient.NotesMessageRecipient.GUID);
	}
}
