/**
 * This class is generated by jOOQ
 */
package com.josh2112.inotesmonitor.database;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in 
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table NotesMeetingAttendee
	 */
	public static final com.josh2112.inotesmonitor.database.tables.NotesMeetingAttendee NotesMeetingAttendee = com.josh2112.inotesmonitor.database.tables.NotesMeetingAttendee.NotesMeetingAttendee;

	/**
	 * The table NotesMeetingDetails
	 */
	public static final com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails NotesMeetingDetails = com.josh2112.inotesmonitor.database.tables.NotesMeetingDetails.NotesMeetingDetails;

	/**
	 * The table NotesMessage
	 */
	public static final com.josh2112.inotesmonitor.database.tables.NotesMessage NotesMessage = com.josh2112.inotesmonitor.database.tables.NotesMessage.NotesMessage;

	/**
	 * The table NotesMessageRecipient
	 */
	public static final com.josh2112.inotesmonitor.database.tables.NotesMessageRecipient NotesMessageRecipient = com.josh2112.inotesmonitor.database.tables.NotesMessageRecipient.NotesMessageRecipient;
}
