--
-- Schema for iNotesMonitor database
-- Joshua Foster, 2014
--

CREATE TABLE IF NOT EXISTS NotesMessage (
	GUID VARCHAR(32) PRIMARY KEY NOT NULL,
	MessageType INTEGER NOT NULL,
	IsRead INTEGER NOT NULL,
	Date TIMESTAMP NOT NULL,
	Sender VARCHAR,
	Subject VARCHAR,
	Body VARCHAR
);

CREATE TABLE IF NOT EXISTS NotesMeetingDetails (
	ID INTEGER PRIMARY KEY NOT NULL,
	MeetingId VARCHAR(32) NOT NULL,
	GUID VARCHAR(32) NOT NULL,
	Chair VARCHAR,
	Topic VARCHAR,
	Location VARCHAR,
	StartDate TIMESTAMP NOT NULL,
	EndDate TIMESTAMP NOT NULL,
	FOREIGN KEY( GUID ) REFERENCES NotesMessage( GUID )
);

CREATE TABLE IF NOT EXISTS NotesMeetingAttendee (
	ID INTEGER PRIMARY KEY NOT NULL,
	MeetingDetailsId INTEGER NOT NULL,
	Name VARCHAR NOT NULL,
	FOREIGN KEY( MeetingDetailsId ) REFERENCES NotesMeetingDetails( ID )
);

CREATE TABLE IF NOT EXISTS NotesMessageRecipient (
	ID INTEGER PRIMARY KEY NOT NULL,
	GUID VARCHAR(32) NOT NULL,
	Name VARCHAR NOT NULL,
	FOREIGN KEY( GUID ) REFERENCES NotesMessage( GUID )
);

