/**
 * This class is generated by jOOQ
 */
package com.josh2112.inotesmonitor.database.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotesMessageRecord extends org.jooq.impl.UpdatableRecordImpl<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecord> implements java.io.Serializable, java.lang.Cloneable, org.jooq.Record7<java.lang.String, com.josh2112.inotesmonitor.inotesdata.NotesMessage.MessageType, java.lang.Boolean, java.time.LocalDateTime, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1010074690;

	/**
	 * Setter for <code>NotesMessage.GUID</code>.
	 */
	public void setGUID(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>NotesMessage.GUID</code>.
	 */
	public java.lang.String getGUID() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>NotesMessage.MessageType</code>.
	 */
	public void setMessageType(com.josh2112.inotesmonitor.inotesdata.NotesMessage.MessageType value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>NotesMessage.MessageType</code>.
	 */
	public com.josh2112.inotesmonitor.inotesdata.NotesMessage.MessageType getMessageType() {
		return (com.josh2112.inotesmonitor.inotesdata.NotesMessage.MessageType) getValue(1);
	}

	/**
	 * Setter for <code>NotesMessage.IsRead</code>.
	 */
	public void setIsRead(java.lang.Boolean value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>NotesMessage.IsRead</code>.
	 */
	public java.lang.Boolean getIsRead() {
		return (java.lang.Boolean) getValue(2);
	}

	/**
	 * Setter for <code>NotesMessage.Date</code>.
	 */
	public void setDate(java.time.LocalDateTime value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>NotesMessage.Date</code>.
	 */
	public java.time.LocalDateTime getDate() {
		return (java.time.LocalDateTime) getValue(3);
	}

	/**
	 * Setter for <code>NotesMessage.Sender</code>.
	 */
	public void setSender(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>NotesMessage.Sender</code>.
	 */
	public java.lang.String getSender() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>NotesMessage.Subject</code>.
	 */
	public void setSubject(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>NotesMessage.Subject</code>.
	 */
	public java.lang.String getSubject() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>NotesMessage.Body</code>.
	 */
	public void setBody(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>NotesMessage.Body</code>.
	 */
	public java.lang.String getBody() {
		return (java.lang.String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.String, com.josh2112.inotesmonitor.inotesdata.NotesMessage.MessageType, java.lang.Boolean, java.time.LocalDateTime, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.String, com.josh2112.inotesmonitor.inotesdata.NotesMessage.MessageType, java.lang.Boolean, java.time.LocalDateTime, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.josh2112.inotesmonitor.database.tables.NotesMessage.NotesMessage.GUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<com.josh2112.inotesmonitor.inotesdata.NotesMessage.MessageType> field2() {
		return com.josh2112.inotesmonitor.database.tables.NotesMessage.NotesMessage.MessageType;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field3() {
		return com.josh2112.inotesmonitor.database.tables.NotesMessage.NotesMessage.IsRead;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.time.LocalDateTime> field4() {
		return com.josh2112.inotesmonitor.database.tables.NotesMessage.NotesMessage.Date;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.josh2112.inotesmonitor.database.tables.NotesMessage.NotesMessage.Sender;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.josh2112.inotesmonitor.database.tables.NotesMessage.NotesMessage.Subject;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.josh2112.inotesmonitor.database.tables.NotesMessage.NotesMessage.Body;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getGUID();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.josh2112.inotesmonitor.inotesdata.NotesMessage.MessageType value2() {
		return getMessageType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value3() {
		return getIsRead();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.time.LocalDateTime value4() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getSender();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getSubject();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getBody();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMessageRecord value1(java.lang.String value) {
		setGUID(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMessageRecord value2(com.josh2112.inotesmonitor.inotesdata.NotesMessage.MessageType value) {
		setMessageType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMessageRecord value3(java.lang.Boolean value) {
		setIsRead(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMessageRecord value4(java.time.LocalDateTime value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMessageRecord value5(java.lang.String value) {
		setSender(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMessageRecord value6(java.lang.String value) {
		setSubject(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMessageRecord value7(java.lang.String value) {
		setBody(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMessageRecord values(java.lang.String value1, com.josh2112.inotesmonitor.inotesdata.NotesMessage.MessageType value2, java.lang.Boolean value3, java.time.LocalDateTime value4, java.lang.String value5, java.lang.String value6, java.lang.String value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached NotesMessageRecord
	 */
	public NotesMessageRecord() {
		super(com.josh2112.inotesmonitor.database.tables.NotesMessage.NotesMessage);
	}

	/**
	 * Create a detached, initialised NotesMessageRecord
	 */
	public NotesMessageRecord(java.lang.String GUID, com.josh2112.inotesmonitor.inotesdata.NotesMessage.MessageType MessageType, java.lang.Boolean IsRead, java.time.LocalDateTime Date, java.lang.String Sender, java.lang.String Subject, java.lang.String Body) {
		super(com.josh2112.inotesmonitor.database.tables.NotesMessage.NotesMessage);

		setValue(0, GUID);
		setValue(1, MessageType);
		setValue(2, IsRead);
		setValue(3, Date);
		setValue(4, Sender);
		setValue(5, Subject);
		setValue(6, Body);
	}
}
