/**
 * This class is generated by jOOQ
 */
package com.josh2112.inotesmonitor.database.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotesMessageRecipientRecord extends org.jooq.impl.UpdatableRecordImpl<com.josh2112.inotesmonitor.database.tables.records.NotesMessageRecipientRecord> implements java.io.Serializable, java.lang.Cloneable, org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1451828520;

	/**
	 * Setter for <code>NotesMessageRecipient.ID</code>.
	 */
	public void setID(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>NotesMessageRecipient.ID</code>.
	 */
	public java.lang.Integer getID() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>NotesMessageRecipient.GUID</code>.
	 */
	public void setGUID(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>NotesMessageRecipient.GUID</code>.
	 */
	public java.lang.String getGUID() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>NotesMessageRecipient.Name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>NotesMessageRecipient.Name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.josh2112.inotesmonitor.database.tables.NotesMessageRecipient.NotesMessageRecipient.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.josh2112.inotesmonitor.database.tables.NotesMessageRecipient.NotesMessageRecipient.GUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.josh2112.inotesmonitor.database.tables.NotesMessageRecipient.NotesMessageRecipient.Name;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getID();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getGUID();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMessageRecipientRecord value1(java.lang.Integer value) {
		setID(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMessageRecipientRecord value2(java.lang.String value) {
		setGUID(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMessageRecipientRecord value3(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotesMessageRecipientRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached NotesMessageRecipientRecord
	 */
	public NotesMessageRecipientRecord() {
		super(com.josh2112.inotesmonitor.database.tables.NotesMessageRecipient.NotesMessageRecipient);
	}

	/**
	 * Create a detached, initialised NotesMessageRecipientRecord
	 */
	public NotesMessageRecipientRecord(java.lang.Integer ID, java.lang.String GUID, java.lang.String Name) {
		super(com.josh2112.inotesmonitor.database.tables.NotesMessageRecipient.NotesMessageRecipient);

		setValue(0, ID);
		setValue(1, GUID);
		setValue(2, Name);
	}
}
